apiVersion: v1
kind: Pod
metadata:
  name: production-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations: # Permiten los siguientes taints:
    - key: "environment" # Busqueda por taint
      operator: "Equal"
      value: "production"
      effect: "NoSchedule" # Entonces deberia ir pal nodo de produccion, en mi caso el lab-scheduling-ds3-m02
  affinity: # Reglas de preferencia de donde se tiene que ejecutar
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # Mientras programa PERO NO en ejecución, si el nodo deja de ser apto entonces paila.
        nodeSelectorTerms:
          - matchExpressions:
              - key: environment # Busqueda por label
                operator: In
                values:
                  - production
